### ISSUE TITLE
Nice beta release

### ISSUE THREAD

**Issue by fedy0** [francis94c/esp-partition-gui#1]
Its a nice first release. Just observed some errors and limitations

Again, I thought it might be cool to be able to launch it from the arduino IDE as a plug-in such as [https://github.com/me-no-dev/EspExceptionDecoder](url), which was developed with java.

Check out [https://github.com/arduino/Arduino](url) too

Forked: Hope to fix some issues I found.

Good job :)

**Comment by francis94c** [comment]
I'll look into this issue first... looks interesting

**Comment by francis94c** [comment]
Done...
